### ISSUE TITLE
Duplicate file paths edge-case #2

### ISSUE THREAD

**Issue by jasonkuhrt** [matthewmueller/file-deps#10]
@MatthewMueller This is currently impossible to catch:

```css
.a { background-image: url('z.png'); }
.b { background-image: url("../fixtures/z.png"); }
```

The reason it is impossible to catch is that we don't have any information about the `path` of the `str` coming in here: https://github.com/MatthewMueller/file-deps/blob/master/lib/css.js#L33

What I would like to suggest/brain-storm is a minimal API change that would provide the `path` of given `str` so that we can rule out dupes more robustly.
