### ISSUE TITLE
Does not recognize multiple background-images properly

### ISSUE THREAD

**Issue by dominicbarnes** [matthewmueller/file-deps#13]
When using multiple backgrounds, this module does not parse `url()` declarations after the first one properly:

```css
a {
  background-image: url('./logo.png'), url('./caret.png');
}
```

The first one (`./logo.png`) gets parsed correctly, but the 2nd (`./caret.png`) is not detected. (and is not rewritten by the consumer)
